"""baseline: initial schema

Revision ID: 10bd97e97fee
Revises: 
Create Date: 2026-07-27 04:50:07.904397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bd97e97fee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enrolments_course_code', table_name='enrolments')
    op.drop_table('enrolments')
    op.create_foreign_key(None, 'assessments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connections', 'users', ['invitee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connections', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enrollments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timetable_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable_entries', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.create_table('enrolments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('course_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['courses.code'], name='enrolments_course_code_fkey'),
    sa.PrimaryKeyConstraint('id', name='enrolments_pkey'),
    sa.UniqueConstraint('user_id', 'course_code', name='uq_user_Enrolment')
    )
    op.create_index('ix_enrolments_course_code', 'enrolments', ['course_code'], unique=False)
    # ### end Alembic commands ###
